In [19]:
import numpy as np
import pandas as pd

In [20]:
v1 = np.arange(5)
print(v1)
v2 = np.arange(1,10,1, dtype=int)
v3 = np.arange(3.5,10.5,2, dtype=float)
print(v2)
print(v3)
v4=np.arange(1,10,2)**2
v5=np.arange(1,10,2)**3
print(v4)
print(v5)

[0 1 2 3 4]
[1 2 3 4 5 6 7 8 9]
[3.5 5.5 7.5 9.5]
[ 1  9 25 49 81]
[  1  27 125 343 729]


In [21]:
v1= np.arange(12)
print(v1)
v2 =v1.reshape(2,6)
print(v2)
print(v1.reshape(3,4, order="F"))



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [22]:
v1 = np.arange(1,5).reshape(2,2)
print(np.arange(1,5))
print(v1)

[1 2 3 4]
[[1 2]
 [3 4]]


In [23]:
v1 = np.arange(24)
print(v1)
v2 = v1.reshape(2,3,2,2, order='f')
print(v2)
print(v2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[[ 0 12]
   [ 6 18]]

  [[ 2 14]
   [ 8 20]]

  [[ 4 16]
   [10 22]]]


 [[[ 1 13]
   [ 7 19]]

  [[ 3 15]
   [ 9 21]]

  [[ 5 17]
   [11 23]]]]
(2, 3, 2, 2)


In [24]:
df = pd.read_csv('data/Ex_GrapeData.csv')
print(df)

    continent  brand  size  period price
0           2      2  10.7   47.65   144
1           2      3  14.0   63.13   215
2           2      2   9.0   58.76   105
3           1      1   8.0   34.88    69
4           2      2  10.0   55.53   134
..        ...    ...   ...     ...   ...
58          1      1   5.0   16.66  21.5
59          2      1  21.0   43.00      
60          2      2   5.0   12.00      
61          2      3  13.0   20.00      
62          2      3  31.0   19.00      

[63 rows x 5 columns]


In [25]:
df = pd.read_excel('data/EX_GrapeData.xlsx')
# print(df.head())
# print(df.tail())
# print(df[:3])
print(df['price'])

0     144.0
1     215.0
2     105.0
3      69.0
4     134.0
      ...  
58     21.5
59      NaN
60      NaN
61      NaN
62      NaN
Name: price, Length: 63, dtype: float64


In [48]:
df = pd.read_csv('data/Ex_GrapeData.csv')
# print(df[df.columns[[0,2,4]]])
print(df.loc[:2, 'continent':'price'])


   continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105


In [49]:
df = pd.read_csv('data/Ex_GrapeData.csv')
df_copy = df.copy()
# print(df_copy.columns)
df_copy2 = df_copy[['size', 'period', 'price']]
# print(df_copy2)
df_copy2.rename(columns={'period':'time'}, inplace=True)
# print(df_copy2.columns)
df_copy2['growth'] = df_copy2['size'] / df_copy2['time']
# print(df_copy2)
del df_copy2['growth']
print(df_copy2.head())

   size   time price
0  10.7  47.65   144
1  14.0  63.13   215
2   9.0  58.76   105
3   8.0  34.88    69
4  10.0  55.53   134


c:\dev\introduction_to_machine_learning_with_python\venv\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
C:\Users\yeoga\AppData\Local\Temp/ipykernel_28424/4099501316.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy2['growth'] = df_copy2['size'] / df_copy2['time']


In [50]:
df = pd.read_csv('data/Ex_GrapeData.csv')
# df_continent_brand = df[]
df_continent_brand = df[(df['continent']==1) & (df['brand'] == 1)]
print(df_continent_brand.head())


    continent  brand  size  period price
3           1      1   8.0   34.88    69
11          1      1  10.4   17.67    54
12          1      1   7.4   16.41    39
13          1      1   5.4   12.02  29.5
16          1      1   6.0   23.21    42


In [51]:
df = pd.read_csv('data/Ex_GrapeData.csv')
df['brand'].value_counts()
recode_brand = {"brand":{1:1, 2:1, 3:2}}
df_recode1 = df.replace(recode_brand)
# df_recode1.head()
df_recode1['brand'].value_counts()

1.0    47
2.0    16
Name: brand, dtype: int64

In [52]:
df = pd.read_csv('data/Ex_GrapeData.csv')
def brand_groups(series):
    if series ==1:
        return 1
    elif series ==2:
        return 1
    elif series ==3:
        return 2
df['re_brand'] = df['brand'].apply(brand_groups)
df.head()

continent  brand  size  period price  re_brand
0          2      2  10.7   47.65   144         1
1          2      3  14.0   63.13   215         2
2          2      2   9.0   58.76   105         1
3          1      1   8.0   34.88    69         1
4          2      2  10.0   55.53   134         1

In [56]:
df = pd.read_csv('data/Ex_GrapeData.csv')
df_num = df.to_numpy()
df_pd = pd.DataFrame(df_num, columns =['continent', 'brand', 'size', 'period', 'price'])
df_pd.head()

continent brand  size period price
0         2     2  10.7  47.65   144
1         2     3  14.0  63.13   215
2         2     2   9.0  58.76   105
3         1     1   8.0  34.88    69
4         2     2  10.0  55.53   134